image: python:3.10-slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PIPENV_VENV_IN_PROJECT: 1
  FOE_BOT_USERNAME: $FOE_BOT_USERNAME
  FOE_BOT_PASSWORD: $FOE_BOT_PASSWORD
  FOE_BOT_WORLD: $FOE_BOT_WORLD
  FOE_BOT_DEEPL_API_KEY: $FOE_BOT_DEEPL_API_KEY

cache:
  paths:
    - .cache/pip
    - .venv/

before_script:
  - pip install pipenv
  - apt-get update
  - apt-get install -y --no-install-recommends gcc upx
  - pipenv install --dev

stages:
  - test
  - package

lint:
  stage: test
  script:
    - pipenv run mypy
    - pipenv run flake8

test:
  stage: test
  before_script:
    - pip install pipenv
    - apt-get update
    - apt-get install -y --no-install-recommends xvfb wget gnupg
    - |-
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&
        echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
    - apt-get update
    - apt-get install -y google-chrome-stable
    - pipenv install --dev
  script:
    - |-
        export DISPLAY=:99 &&
        Xvfb :99 -ac -screen 0 ${XVFB_WHD:-1280x720x16} -nolisten tcp &
        pipenv run pytest --cov --cov-fail-under=90 --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml

package-linux:
  stage: package
  only:
    - master
  script:
    - pipenv run pyinstaller --name foe-bot --onefile --windowed ./foe_bot/app.py
  artifacts:
    paths:
      - dist/foe-bot
    expire_in: 4 weeks

package-windows:
  stage: package
  only:
      - master
  image: tobix/pywine:3.10
  before_script:
      - wine pip install pipenv
      - wine pipenv install --dev
  script:
    - wine pipenv run pyinstaller --name foe-bot --onefile --windowed ./foe_bot/app.py
  artifacts:
    paths:
      - dist/foe-bot.exe
    expire_in: 4 weeks

