import attr


@attr.define
class Resources:
    expansions: int = attr.ib(default=None)
    premium: int = attr.ib(default=None)
    guild_expedition_attempt: int = attr.ib(default=None)
    tavern_silver: int = attr.ib(default=None)
    stars: int = attr.ib(default=None)
    carnival_roses: int = attr.ib(default=None)
    carnival_hearts: int = attr.ib(default=None)
    spring_lanterns: int = attr.ib(default=None)
    forge_bowl_footballs: int = attr.ib(default=None)
    carnival_coins: int = attr.ib(default=None)
    carnival_tickets: int = attr.ib(default=None)
    soccer_energy: int = attr.ib(default=None)
    summer_doubloons: int = attr.ib(default=None)
    summer_compass: int = attr.ib(default=None)
    fall_ingredient_apples: int = attr.ib(default=None)
    fall_ingredient_pumpkins: int = attr.ib(default=None)
    fall_ingredient_chocolate: int = attr.ib(default=None)
    fall_ingredient_cinnamon: int = attr.ib(default=None)
    fall_ingredient_caramel: int = attr.ib(default=None)
    winter_matches: int = attr.ib(default=None)
    archeology_brush: int = attr.ib(default=None)
    archeology_shovel: int = attr.ib(default=None)
    archeology_dynamite: int = attr.ib(default=None)
    archeology_scroll: int = attr.ib(default=None)
    halloween_candle: int = attr.ib(default=None)
    halloween_flashlight: int = attr.ib(default=None)
    halloween_lantern: int = attr.ib(default=None)
    halloween_ticket: int = attr.ib(default=None)
    winter_reindeer: int = attr.ib(default=None)
    st_patricks_pot_of_gold: int = attr.ib(default=None)
    soccer_tournament_tickets: int = attr.ib(default=None)
    pvp_arena_attempt: int = attr.ib(default=None)
    archeology_gem_shard: int = attr.ib(default=None)
    wildlife_pop_moves: int = attr.ib(default=None)
    wildlife_tickets: int = attr.ib(default=None)
    wildlife_coins: int = attr.ib(default=None)
    wildlife_booster_hammer: int = attr.ib(default=None)
    wildlife_booster_color_changer: int = attr.ib(default=None)
    wildlife_booster_color_destroyer: int = attr.ib(default=None)
    halloween_joker_sticker: int = attr.ib(default=None)
    winter_master_key_parts: int = attr.ib(default=None)
    guild_perks_daily_donations: int = attr.ib(default=None)
    strategy_points: int = attr.ib(default=None)  # forge points
    money: int = attr.ib(default=None)
    medals: int = attr.ib(default=None)
    population: int = attr.ib(default=None)
    total_population: int = attr.ib(default=None)
    castle_points: int = attr.ib(default=None)
    supplies: int = attr.ib(default=None)

    raw_silk: int = attr.ib(default=None)
    raw_sandstone: int = attr.ib(default=None)
    raw_textiles: int = attr.ib(default=None)
    raw_ebony: int = attr.ib(default=None)
    raw_asbestos: int = attr.ib(default=None)
    raw_ropes: int = attr.ib(default=None)
    raw_gunpowder: int = attr.ib(default=None)
    raw_salt: int = attr.ib(default=None)
    raw_fusion_reactors: int = attr.ib(default=None)
    raw_wire: int = attr.ib(default=None)
    raw_honey: int = attr.ib(default=None)
    raw_nickel: int = attr.ib(default=None)
    raw_glowing_seaweed: int = attr.ib(default=None)
    raw_sugar_crystals: int = attr.ib(default=None)
    raw_talc: int = attr.ib(default=None)
    raw_paper: int = attr.ib(default=None)
    raw_processed_material: int = attr.ib(default=None)
    raw_wine: int = attr.ib(default=None)
    raw_glass: int = attr.ib(default=None)
    raw_granite: int = attr.ib(default=None)
    raw_herbs: int = attr.ib(default=None)
    raw_lead: int = attr.ib(default=None)
    raw_lubricants: int = attr.ib(default=None)
    raw_brick: int = attr.ib(default=None)
    raw_platinum_crystals: int = attr.ib(default=None)
    raw_gold: int = attr.ib(default=None)
    raw_compound_fluid: int = attr.ib(default=None)
    raw_superalloys: int = attr.ib(default=None)
    raw_tar: int = attr.ib(default=None)
    raw_porcelain: int = attr.ib(default=None)
    raw_limestone: int = attr.ib(default=None)
    raw_cloth: int = attr.ib(default=None)
    raw_machineparts: int = attr.ib(default=None)
    raw_soy_proteins: int = attr.ib(default=None)
    raw_fertilizer: int = attr.ib(default=None)
    raw_alabaster: int = attr.ib(default=None)
    raw_bromine: int = attr.ib(default=None)
    raw_marble: int = attr.ib(default=None)
    raw_dye: int = attr.ib(default=None)
    raw_cypress: int = attr.ib(default=None)
    raw_microgreen_supplement: int = attr.ib(default=None)
    raw_mars_microbes: int = attr.ib(default=None)
    raw_coffee: int = attr.ib(default=None)
    raw_brass: int = attr.ib(default=None)
    raw_biotech_crops: int = attr.ib(default=None)
    raw_herbal_snack: int = attr.ib(default=None)
    raw_explosives: int = attr.ib(default=None)
    raw_tinplate: int = attr.ib(default=None)
    raw_gems: int = attr.ib(default=None)
    raw_bronze: int = attr.ib(default=None)
    raw_whaleoil: int = attr.ib(default=None)
    raw_rubber: int = attr.ib(default=None)
    raw_coke: int = attr.ib(default=None)
    raw_petroleum: int = attr.ib(default=None)
    raw_basalt: int = attr.ib(default=None)

@attr.define
class ResourcesWrapper:
    resources: Resources
    klass: str
